name: Bug report
description: Use this form to report reproducible bugs. Please include steps and environment details.
title: "Bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Fill in the details below to help us reproduce and fix it.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A short summary of the problem
      placeholder: "e.g. Crash when opening settings"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the bug in order
      placeholder: "1. Open ...\n2. Click ...\n3. Observe ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Version number, commit hash, or release
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - label: Blocker
          value: blocker
        - label: High
          value: high
        - label: Medium
          value: medium
        - label: Low
          value: low
  - type: textarea
    id: logs
    attributes:
      label: Logs / stack traces
      description: Paste any logs or stack traces here
  - type: markdown
    attributes:
      value: |
        _You can add screenshots or attach files using the issue editor's upload control._
